[package]
name = "libload-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libloading = "0.7.4"
ouroboros = "0.15.5"


[workspace]
members = ["mylib"]